# Generated by Django 4.1.3 on 2023-08-08 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0003_draw_ticketprice_agentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('choosen_number', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('winner', models.BooleanField(default=False)),
                ('settled', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.ticketprice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_bought', to=settings.AUTH_USER_MODEL)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.draw')),
            ],
        ),
    ]
