# Generated by Django 4.1.3 on 2023-08-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0007_order_a_order_ab_order_abc_order_ac_order_b_order_bc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processing', 'processing'), ('accepted', 'accepted'), ('cancelled', 'cancelled')], default='processing', max_length=30),
        ),
    ]
