# Generated by Django 4.1.3 on 2023-08-08 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0008_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_status', models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], max_length=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.draw')),
            ],
        ),
    ]
