# Generated by Django 4.1.3 on 2023-08-08 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0009_agentcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcollection',
            name='amount_to_collect',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentcollection',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentcollection',
            name='collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentcollection',
            name='collection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentcollection',
            name='collection_status',
            field=models.CharField(blank=True, choices=[('partial', 'Partial'), ('full', 'Full')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agentcollection',
            name='draw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.draw'),
        ),
    ]
