# Generated by Django 4.1.3 on 2023-08-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0010_agentcollection_amount_to_collect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='upi_reference_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_upi_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='upi_transaction_reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
