# Generated by Django 4.1.3 on 2023-08-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0011_remove_order_upi_reference_id_order_payment_upi_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=250, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=250, null=True)),
                ('gpay', models.CharField(blank=True, max_length=250, null=True)),
                ('phonepe', models.CharField(blank=True, max_length=250, null=True)),
                ('paytm', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('background', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('loader_image', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('loader_image_two', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('additional_info', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('theme_color_one', models.CharField(blank=True, max_length=250, null=True)),
                ('theme_color_two', models.CharField(blank=True, max_length=250, null=True)),
                ('button_color', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
