# Generated by Django 4.1.3 on 2023-08-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0012_websiteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprice',
            name='ticket_winning_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
