# Generated by Django 4.1.3 on 2023-08-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0013_ticketprice_ticket_winning_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='A',
        ),
        migrations.RemoveField(
            model_name='order',
            name='AB',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ABC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='AC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='B',
        ),
        migrations.RemoveField(
            model_name='order',
            name='BC',
        ),
        migrations.RemoveField(
            model_name='order',
            name='C',
        ),
        migrations.CreateModel(
            name='OrderCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.TextField(blank=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.ticketprice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.order')),
            ],
        ),
    ]
