# Generated by Django 4.1.3 on 2023-08-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0018_draw_is_active_draw_result_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='orders_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
