# Generated by Django 4.1.3 on 2023-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0019_draw_orders_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprice',
            name='board_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
