# Generated by Django 4.1.3 on 2023-08-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0020_ticketprice_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketprice',
            name='board_name',
        ),
        migrations.RemoveField(
            model_name='ticketprice',
            name='ticket_winning_value',
        ),
        migrations.AddField(
            model_name='ticket',
            name='winning_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BoardWinngPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(blank=True, max_length=255, null=True)),
                ('winning_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ticket_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.ticketprice')),
            ],
        ),
    ]
