# Generated by Django 4.1.3 on 2023-08-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0023_agentwinning'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='winning_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('processing', 'processing'), ('accepted', 'accepted'), ('cancelled', 'cancelled'), ('settled', 'settled')], default='processing', max_length=30),
        ),
    ]
