# Generated by Django 4.1.3 on 2023-08-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0024_order_winning_amount_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentwinning',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
