# Generated by Django 4.1.3 on 2023-08-13 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0026_ticketprice_commision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentcollectionbalance',
            old_name='collection_amount',
            new_name='total_collection_amount',
        ),
        migrations.AlterField(
            model_name='agentcollectionbalance',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
