# Generated by Django 4.1.3 on 2023-08-13 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0029_walletbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_approved', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_address', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='KuberaApp.customerbalance')),
            ],
            options={
                'unique_together': {('transaction_id', 'upi_address')},
            },
        ),
        migrations.DeleteModel(
            name='WalletBalance',
        ),
    ]
