# Generated by Django 4.1.3 on 2023-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0031_customerbalancehistory_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerbalancehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customerbalancehistory',
            name='unique_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
