# Generated by Django 4.1.3 on 2023-08-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0034_user_bank_account_number_user_bank_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
