# Generated by Django 4.1.3 on 2023-08-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KuberaApp', '0036_orderapproval'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderapproval',
            unique_together={('transaction_id', 'upi_address')},
        ),
    ]
